import * as THREE from 'three';
import { ParticleSystem } from '@kairo/renderer';
import { ForestAudio } from '../audio/ForestAudio.ts';
export declare class FoxPlayer {
    position: THREE.Vector3;
    velocity: THREE.Vector3;
    rotationY: number;
    isGrounded: boolean;
    airJumpsLeft: number;
    isPouncing: boolean;
    invulnerabilityTimer: number;
    container: THREE.Group;
    private loadedModel;
    private fallbackGroup;
    private animStateMachine;
    walkSpeed: number;
    pounceSpeed: number;
    jumpForce: number;
    private barkTimer;
    private auraRing;
    private auraMaterial;
    private dustParticles;
    private sparkleParticles;
    private audio;
    constructor(scene: THREE.Scene, dustParticles: ParticleSystem, sparkleParticles: ParticleSystem, audio: ForestAudio);
    private createFallbackFox;
    private loadFoxModel;
    jump(): boolean;
    pounce(): boolean;
    spiritBark(): boolean;
    takeDamage(knockbackDir?: THREE.Vector3): void;
    setGoldenAura(): void;
    update(dt: number, inputX: number, inputZ: number, getTerrainHeight: (x: number, z: number) => number, camYaw?: number): void;
}
