import type { QuestSystem, DialogueSystem } from '@kairo/core';
export interface ObjectiveItem {
    id: string;
    text: string;
    isCompleted: boolean;
}
export declare class GameHUD {
    private startScreenEl;
    private startNewBtnEl;
    private startContinueBtnEl;
    private saveInfoPreviewEl;
    private saveWispsCountEl;
    private saveAcornsCountEl;
    private startResetSaveBtnEl;
    private acornValEl;
    private staminaFillEl;
    private realmPillEl;
    private questChapterTagEl;
    private questTextEl;
    private questObjectivesListEl;
    private spiritRankBadgeEl;
    private actionToastEl;
    private toastIconEl;
    private toastTextEl;
    private soundBtnEl;
    private photoBtnEl;
    private photoModeUIEl;
    private photoExitBtnEl;
    private photoCaptureBtnEl;
    private victoryModalEl;
    private finalAcornsEl;
    private finalTimeEl;
    private victoryContinueBtnEl;
    private dialogueBoxEl;
    private npcAvatarEl;
    private npcNameEl;
    private npcTextEl;
    private dialogueCloseBtnEl;
    private toastTimeout;
    private quests?;
    private dialogue?;
    constructor(onStartGame: (isContinue: boolean) => void, onCaptureScreenshot: () => void, onPlayClickSound: () => void, quests?: QuestSystem, dialogue?: DialogueSystem);
    checkSavedGame(): void;
    syncSavedUI(): void;
    updateRealm(level: number): void;
    updateHearts(hearts: number, maxHearts?: number): void;
    renderQuestObjectives(): void;
    showToast(text: string, icon?: string): void;
    showDialogue(speaker: string, avatar: string, text: string): void;
    hideDialogue(): void;
    togglePhotoMode(): boolean;
    updateStamina(stamina: number, maxStamina: number): void;
    showVictoryModal(): void;
}
